package com.gavin.epidemic.model;

import java.util.Date;

public class Epidemics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.serial_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Integer serialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.province_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.data_year
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Short dataYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.data_month
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Short dataMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.data_day
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Short dataDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.affirmed
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Integer affirmed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.suspected
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Integer suspected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.isolated
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Integer isolated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.dead
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Integer dead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.cured
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Integer cured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.user_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemics.input_date
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Date inputDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.serial_id
     *
     * @return the value of epidemics.serial_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Integer getSerialId() {
        return serialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.serial_id
     *
     * @param serialId the value for epidemics.serial_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setSerialId(Integer serialId) {
        this.serialId = serialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.province_id
     *
     * @return the value of epidemics.province_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.province_id
     *
     * @param provinceId the value for epidemics.province_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.data_year
     *
     * @return the value of epidemics.data_year
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Short getDataYear() {
        return dataYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.data_year
     *
     * @param dataYear the value for epidemics.data_year
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setDataYear(Short dataYear) {
        this.dataYear = dataYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.data_month
     *
     * @return the value of epidemics.data_month
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Short getDataMonth() {
        return dataMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.data_month
     *
     * @param dataMonth the value for epidemics.data_month
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setDataMonth(Short dataMonth) {
        this.dataMonth = dataMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.data_day
     *
     * @return the value of epidemics.data_day
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Short getDataDay() {
        return dataDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.data_day
     *
     * @param dataDay the value for epidemics.data_day
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setDataDay(Short dataDay) {
        this.dataDay = dataDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.affirmed
     *
     * @return the value of epidemics.affirmed
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Integer getAffirmed() {
        return affirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.affirmed
     *
     * @param affirmed the value for epidemics.affirmed
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setAffirmed(Integer affirmed) {
        this.affirmed = affirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.suspected
     *
     * @return the value of epidemics.suspected
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Integer getSuspected() {
        return suspected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.suspected
     *
     * @param suspected the value for epidemics.suspected
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setSuspected(Integer suspected) {
        this.suspected = suspected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.isolated
     *
     * @return the value of epidemics.isolated
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Integer getIsolated() {
        return isolated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.isolated
     *
     * @param isolated the value for epidemics.isolated
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setIsolated(Integer isolated) {
        this.isolated = isolated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.dead
     *
     * @return the value of epidemics.dead
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Integer getDead() {
        return dead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.dead
     *
     * @param dead the value for epidemics.dead
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setDead(Integer dead) {
        this.dead = dead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.cured
     *
     * @return the value of epidemics.cured
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Integer getCured() {
        return cured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.cured
     *
     * @param cured the value for epidemics.cured
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setCured(Integer cured) {
        this.cured = cured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.user_id
     *
     * @return the value of epidemics.user_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.user_id
     *
     * @param userId the value for epidemics.user_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epidemics.input_date
     *
     * @return the value of epidemics.input_date
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epidemics.input_date
     *
     * @param inputDate the value for epidemics.input_date
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }
}