package com.gavin.epidemic.model;

public class Provinces {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.province_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.province_name
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.province_py
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private String provincePy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.del_flag
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    private Short delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.province_id
     *
     * @return the value of provinces.province_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.province_id
     *
     * @param provinceId the value for provinces.province_id
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.province_name
     *
     * @return the value of provinces.province_name
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.province_name
     *
     * @param provinceName the value for provinces.province_name
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.province_py
     *
     * @return the value of provinces.province_py
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public String getProvincePy() {
        return provincePy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.province_py
     *
     * @param provincePy the value for provinces.province_py
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setProvincePy(String provincePy) {
        this.provincePy = provincePy == null ? null : provincePy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.del_flag
     *
     * @return the value of provinces.del_flag
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.del_flag
     *
     * @param delFlag the value for provinces.del_flag
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }
}