package com.gavin.epidemic.mapper;

import com.gavin.epidemic.model.Epidemics;
import com.gavin.epidemic.model.EpidemicsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EpidemicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    long countByExample(EpidemicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int deleteByExample(EpidemicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int deleteByPrimaryKey(Integer serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int insert(Epidemics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int insertSelective(Epidemics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    List<Epidemics> selectByExampleWithRowbounds(EpidemicsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    List<Epidemics> selectByExample(EpidemicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    Epidemics selectByPrimaryKey(Integer serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") Epidemics record, @Param("example") EpidemicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int updateByExample(@Param("record") Epidemics record, @Param("example") EpidemicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int updateByPrimaryKeySelective(Epidemics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemics
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int updateByPrimaryKey(Epidemics record);
}