package com.gavin.epidemic.mapper;

import com.gavin.epidemic.model.Provinces;
import com.gavin.epidemic.model.ProvincesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProvincesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    long countByExample(ProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int deleteByExample(ProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int deleteByPrimaryKey(Integer provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int insert(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int insertSelective(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    List<Provinces> selectByExampleWithRowbounds(ProvincesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    List<Provinces> selectByExample(ProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    Provinces selectByPrimaryKey(Integer provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") Provinces record, @Param("example") ProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int updateByExample(@Param("record") Provinces record, @Param("example") ProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int updateByPrimaryKeySelective(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbg.generated Tue Jun 23 13:03:52 CST 2020
     */
    int updateByPrimaryKey(Provinces record);
}